# Generated by Django 5.1.2 on 2026-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='auto_approve_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_low_stock_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
