# Generated by Django 5.1.2 on 2026-04-01 09:59

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
        ('vendors', '0003_vendorprofile_auto_approve_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(help_text='e.g., Samagri Store, Book Store', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='vendor_ids/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage taken by platform', max_digits=5)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_accepting_orders', models.BooleanField(default=True)),
                ('auto_approve_orders', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_low_stock_alert_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Account',
                'verbose_name_plural': 'Vendor Accounts',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
