# Generated by Django 5.1.2 on 2026-04-01 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_manual_data_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='auto_approve_orders',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_accepting_orders',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_low_stock_alert_enabled',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='notification_email',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='verification_status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='verification_status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
