# Generated by Django 5.1.2 on 2026-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_pandit_alter_chatroom_pandit_and_more'),
        ('vendors', '0005_remove_vendorprofile_auto_approve_orders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
