# Generated by Django 5.2.10 on 2026-01-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0008_remove_pandit_available_balance_and_more'),
        ('payments', '0002_payment_amount_npr_payment_amount_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanditWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='pandits.pandit')),
            ],
        ),
    ]
