# Generated by Django 5.1.2 on 2026-04-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_panditwithdrawal'),
        ('pandits', '0012_global_pandit_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panditwithdrawal',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='pandits.pandituser'),
        ),
    ]
