# Generated by Django 5.2.10 on 2026-01-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samagriitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
