# Generated by Django 5.1.2 on 2026-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0003_samagriitem_created_at_samagriitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samagriitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='samagri_images/'),
        ),
    ]
