# Generated by Django 5.1.2 on 2026-02-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0004_samagriitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='samagri_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samagri.samagriitem'),
        ),
    ]
