# Generated by Django 5.1.2 on 2026-02-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0005_shoporderitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samagricategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Samagri Categories'},
        ),
        migrations.AddField(
            model_name='samagricategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='samagricategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='samagricategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='samagricategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='samagricategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
