# Generated by Django 5.1.2 on 2026-02-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0006_alter_samagricategory_options_samagricategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samagricategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
