# Generated by Django 5.1.2 on 2026-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samagricategory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
