# Generated by Django 5.1.2 on 2026-03-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0010_samagriitem_price_usd'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samagriitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorprofile'),
        ),
    ]
