# Generated by Django 5.1.2 on 2026-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0011_samagriitem_vendor_shoporderitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='samagriitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
