# Generated by Django 5.1.2 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0012_samagriitem_is_approved'),
        ('vendors', '0005_remove_vendorprofile_auto_approve_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samagriitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='shoporderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor'),
        ),
    ]
