# Generated by Django 5.1.2 on 2026-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagri', '0013_alter_samagriitem_vendor_alter_shoporderitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='buyer_role',
            field=models.CharField(default='user', help_text='Role of the user when placing the order', max_length=20),
        ),
    ]
