# Generated by Django 5.2.10 on 2026-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puja',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='puja',
            name='pandit',
        ),
        migrations.RemoveField(
            model_name='puja',
            name='price',
        ),
        migrations.AddField(
            model_name='puja',
            name='base_duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='puja',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='puja',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puja_images/'),
        ),
    ]
