# Generated by Django 5.1.2 on 2026-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pujacategory_puja_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='puja',
            name='base_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
