# Generated by Django 5.1.2 on 2026-03-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('mobile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_type', models.CharField(choices=[('MAIN_BANNER', 'Main Banner'), ('SALE_BANNER', 'Sale Banner'), ('FESTIVAL_BANNER', 'Festival Banner'), ('OFFER_BANNER', 'Offer Banner'), ('DISCOUNT_BANNER', 'Discount Banner')], default='MAIN_BANNER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled')], default='ACTIVE', max_length=10)),
                ('priority_order', models.IntegerField(default=1)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority_order', '-created_at'],
            },
        ),
    ]
