# Generated by Django 5.2.10 on 2026-01-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundali',
            name='lagna',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kundali',
            name='midheaven',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='KundaliHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField()),
                ('cusp_longitude', models.FloatField()),
                ('kundali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='kundali.kundali')),
            ],
        ),
    ]
