# Generated by Django 5.1.2 on 2026-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundali', '0003_kundali_ai_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundali',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='kundali',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
    ]
