# Generated by Django 5.2.10 on 2026-01-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_chatmessage_dual_mode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_mode_12cbdf_idx',
            old_name='chat_chatme_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_booking_ae106f_idx',
            old_name='chat_chatme_booking_idx',
        ),
    ]
