# Generated by Django 5.1.2 on 2026-03-12 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_daily_room_name_booking_daily_room_url_and_more'),
        ('chat', '0003_rename_chat_chatme_mode_idx_chat_chatme_mode_12cbdf_idx_and_more'),
        ('pandits', '0010_panditavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_pre_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='bookings.booking'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'pandit', 'is_pre_booking')},
        ),
    ]
