# Generated by Django 5.1.2 on 2026-03-28 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_is_pre_booking_alter_chatroom_booking_and_more'),
        ('pandits', '0010_panditavailability'),
        ('samagri', '0012_samagriitem_is_approved'),
        ('vendors', '0003_vendorprofile_auto_approve_orders_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_chats', to='samagri.shoporder'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_chats', to='vendors.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='pandit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pandit_chats', to='pandits.pandit'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'pandit', 'vendor', 'is_pre_booking')},
        ),
    ]
