# Generated by Django 5.1.2 on 2026-04-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_unique_together_chatroom_order_and_more'),
        ('pandits', '0012_global_pandit_fix'),
        ('vendors', '0004_manual_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='pandit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to='pandits.pandituser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='pandit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pandit_chats', to='pandits.pandituser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_chats', to='vendors.vendor'),
        ),
    ]
