# Generated by Django 5.2.9 on 2025-12-31 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_rename_fee_booking_samagri_fee_booking_accepted_at_and_more'),
        ('pandits', '0005_alter_pandit_options_pandit_certification_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('comment_ne', models.TextField(blank=True, null=True, verbose_name='Comment (Nepali)')),
                ('professionalism', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pandits.pandit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pandit', '-created_at'], name='reviews_rev_pandit__db402d_idx'), models.Index(fields=['customer'], name='reviews_rev_custome_931f64_idx')],
            },
        ),
    ]
