# Generated by Django 5.1.2 on 2026-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_pandit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('pandit', 'Pandit'), ('vendor', 'Vendor')], default='customer', max_length=10),
        ),
    ]
