# Generated by Django 5.2.10 on 2026-01-09 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_booking_total_fee_usd_booking_video_room_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='daily', max_length=20)),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_url', models.URLField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_room', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='VideoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_participations', to=settings.AUTH_USER_MODEL)),
                ('video_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video.videoroom')),
            ],
        ),
        migrations.CreateModel(
            name='VudeoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vudeo_participants', to='video.videoroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vudeo_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
