# Generated by Django 5.2.10 on 2026-01-09 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoparticipant',
            old_name='video_room',
            new_name='room',
        ),
        migrations.AddField(
            model_name='videoparticipant',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoparticipant',
            name='role',
            field=models.CharField(choices=[('pandit', 'Pandit'), ('customer', 'Customer')], default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='videoparticipant',
            unique_together={('room', 'user')},
        ),
        migrations.DeleteModel(
            name='VudeoParticipant',
        ),
    ]
