# Generated by Django 5.1.2 on 2026-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_video_room_videoparticipant_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
