# Generated by Django 5.2.8 on 2025-11-26 06:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_location', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACCEPTED', 'Accepted by Pandit'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_appointments', to='pandits.pandit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'unique_together': {('pandit', 'booking_date', 'booking_time')},
            },
        ),
    ]
