# Generated by Django 5.2.9 on 2025-12-31 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fee',
            new_name='samagri_fee',
        ),
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Customer special requests or notes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='samagri_required',
            field=models.BooleanField(default=True, help_text='Include samagri in booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.puja'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_location',
            field=models.CharField(choices=[('ONLINE', 'Online (Video Call)'), ('HOME', 'Customer Home'), ('TEMPLE', 'Temple'), ('PANDIT_LOCATION', "Pandit's Location")], default='ONLINE', max_length=20),
        ),
    ]
