# Generated by Django 5.2.9 on 2026-01-04 15:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_fee_booking_samagri_fee_booking_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSamagriItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECOMMENDED', 'AI Recommended'), ('SELECTED', 'User Selected'), ('AUTO_ADDED', 'Auto Added'), ('REMOVED', 'User Removed')], default='RECOMMENDED', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_essential', models.BooleanField(default=False, help_text='Cannot be removed from booking')),
                ('is_optional', models.BooleanField(default=True, help_text='User can choose to include or exclude')),
                ('is_included', models.BooleanField(default=True, help_text='User chose to include this item')),
                ('reason', models.TextField(blank=True, help_text='Why this item is recommended')),
                ('user_notes', models.TextField(blank=True, help_text="User's notes about this item")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samagri_items', to='bookings.booking')),
            ],
            options={
                'ordering': ['-is_essential', 'created_at'],
            },
        ),
    ]
