# Generated by Django 5.2.9 on 2026-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingsamagriitem'),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsamagriitem',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='recommender.samagrirecommendation'),
        ),
    ]
