# Generated by Django 5.2.9 on 2026-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingsamagriitem_recommendation'),
        ('samagri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsamagriitem',
            name='samagri_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_bookings', to='samagri.samagriitem'),
        ),
        migrations.AddIndex(
            model_name='bookingsamagriitem',
            index=models.Index(fields=['booking', 'is_included'], name='bookings_bo_booking_0aa12f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsamagriitem',
            index=models.Index(fields=['status'], name='bookings_bo_status_ea0041_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingsamagriitem',
            unique_together={('booking', 'samagri_item')},
        ),
    ]
