# Generated by Django 5.2.10 on 2026-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingsamagriitem_samagri_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_location',
            field=models.CharField(choices=[('ONLINE', 'Online (Video Call)'), ('HOME', 'Customer Home'), ('TEMPLE', 'Temple'), ('PANDIT_LOCATION', "Pandit's Location")], default='ONLINE', max_length=50),
        ),
    ]
