# Generated by Django 5.2.10 on 2026-01-09 07:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fee_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='video_room_url',
            field=models.URLField(blank=True, help_text='Video call link for online puja', max_length=500, null=True),
        ),
    ]
