# Generated by Django 5.2.10 on 2026-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_total_fee_usd_booking_video_room_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment Gateway Transaction ID', max_length=100, null=True),
        ),
    ]
