# Generated by Django 5.2.10 on 2026-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_location',
            field=models.CharField(blank=True, help_text='Lat/Long of customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_timezone',
            field=models.CharField(default='UTC', help_text="Customer's local timezone", max_length=50),
        ),
    ]
