# Generated by Django 5.1.2 on 2026-02-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_customer_location_booking_customer_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Recorded session URL (post-puja)', max_length=500, null=True),
        ),
    ]
