# Generated by Django 5.1.2 on 2026-02-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_recording_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
