# Generated by Django 5.1.2 on 2026-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='daily_room_name',
            field=models.CharField(blank=True, help_text='Daily.co room name for webhooks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='daily_room_url',
            field=models.URLField(blank=True, help_text='Official Daily.co join URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='puja_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='puja_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recording_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='video_room_url',
            field=models.URLField(blank=True, help_text='Video call link for online puja (Legacy)', max_length=500, null=True),
        ),
    ]
