# Generated by Django 5.1.2 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_daily_room_name_booking_daily_room_url_and_more'),
        ('pandits', '0012_global_pandit_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_appointments', to='pandits.pandituser'),
        ),
    ]
