# Generated by Django 5.1.2 on 2026-04-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_booking_pandit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.OneToOneField(blank=True, help_text='Tracks the original booking this was rescheduled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACCEPTED', 'Accepted by Pandit'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Payment Failed'), ('MISSED', 'Missed by User'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20),
        ),
    ]
