# Generated by Django 5.1.2 on 2026-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_rescheduled_from_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_address',
            field=models.TextField(blank=True, help_text='Specific address for HOME/TEMPLE/PANDIT_LOCATION rituals', null=True),
        ),
    ]
