# Generated by Django 5.2.8 on 2025-11-20 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number (e.g., 98XXXXXXXX).', regex='^(?:\\+977)?9[78]\\d{8}$')]),
        ),
    ]
