# Generated by Django 5.2.10 on 2026-01-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of booking amount taken as platform commission (e.g., 10.00 for 10%)', max_digits=5)),
                ('video_call_rate_per_min', models.DecimalField(decimal_places=2, default=15.0, help_text='Default rate per minute for video calls (if not overridden by Pandit)', max_digits=10)),
            ],
        ),
    ]
