# Generated by Django 5.1.2 on 2026-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
