# Generated by Django 5.1.2 on 2026-03-12 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_profile_pic_url_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pandit', 'Pandit'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=12),
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero_title', 'Home Hero Title'), ('hero_subtitle', 'Home Hero Subtitle'), ('about_title', 'About Page Title'), ('about_text', 'About Page Text'), ('contact_address', 'Contact Address'), ('contact_phone', 'Contact Phone'), ('contact_email', 'Contact Email'), ('announcement', 'Festival Announcement'), ('footer_text', 'Footer Text')], max_length=50, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['key'],
            },
        ),
    ]
