# Generated by Django 5.1.2 on 2026-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pandit', 'Pandit'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('audit', 'Audit'), ('superadmin', 'Super Admin')], default='user', max_length=12),
        ),
    ]
