# Generated by Django 5.1.2 on 2026-03-13 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(default='guide', max_length=20)),
                ('user_message', models.TextField()),
                ('ai_reply', models.TextField(blank=True, default='')),
                ('response_type', models.CharField(default='text', max_length=50)),
                ('tool_log', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
