# Generated by Django 5.2.8 on 2025-11-26 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0003_alter_pandit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='full_name',
        ),
        migrations.AddField(
            model_name='pandit',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pandit',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pandit',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='expertise',
            field=models.CharField(help_text="Areas of expertise, e.g., 'Vedic', 'Astrology'", max_length=255),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
