# Generated by Django 5.2.9 on 2025-12-31 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0004_remove_pandit_full_name_pandit_date_joined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandit',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='pandit',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='pandit_certifications/'),
        ),
        migrations.AddField(
            model_name='pandit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pandit',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pandit',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='pandit',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pandit',
            index=models.Index(fields=['verification_status'], name='pandits_pan_verific_dfc684_idx'),
        ),
        migrations.AddIndex(
            model_name='pandit',
            index=models.Index(fields=['is_verified'], name='pandits_pan_is_veri_591e6c_idx'),
        ),
    ]
