# Generated by Django 5.2.10 on 2026-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0005_alter_pandit_options_pandit_certification_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandit',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pandit',
            name='pandits_pan_verific_dfc684_idx',
        ),
        migrations.RemoveIndex(
            model_name='pandit',
            name='pandits_pan_is_veri_591e6c_idx',
        ),
        migrations.AlterField(
            model_name='pandit',
            name='expertise',
            field=models.CharField(max_length=255),
        ),
    ]
