# Generated by Django 5.2.10 on 2026-01-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0007_pandit_available_balance_pandit_total_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='pandit',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='pandit',
            name='withdrawn_amount',
        ),
        migrations.CreateModel(
            name='PanditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pandit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='pandits.pandit')),
            ],
        ),
        migrations.DeleteModel(
            name='PanditWithdrawal',
        ),
    ]
