# Generated by Django 5.2.10 on 2026-01-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0008_remove_pandit_available_balance_and_more'),
        ('services', '0002_remove_puja_duration_minutes_remove_puja_pandit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanditService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, help_text="Pandit's price overrides base price", max_digits=10)),
                ('duration_minutes', models.IntegerField(help_text='Estimated time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_offline', models.BooleanField(default=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pandits.pandit')),
                ('puja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_offerings', to='services.puja')),
            ],
            options={
                'unique_together': {('pandit', 'puja')},
            },
        ),
    ]
