# Generated by Django 5.1.2 on 2026-02-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0009_panditservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanditAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('title', models.CharField(default='Unavailable', help_text='Reason for unavailability', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='pandits.pandit')),
            ],
        ),
    ]
