# Generated by Django 5.1.2 on 2026-04-01 09:59

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0010_panditavailability'),
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanditUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expertise', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField(default='')),
                ('is_available', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='pandit_certifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pandit Account',
                'verbose_name_plural': 'Pandit Accounts',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
