# Generated by Django 5.1.2 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0011_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='verification_notes',
        ),
        migrations.AlterField(
            model_name='pandit',
            name='verification_status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='panditavailability',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='pandits.pandituser'),
        ),
        migrations.AlterField(
            model_name='panditavailability',
            name='title',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
        migrations.AlterField(
            model_name='panditservice',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='panditservice',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='panditservice',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pandits.pandituser'),
        ),
        migrations.AlterField(
            model_name='panditwallet',
            name='pandit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='pandits.pandituser'),
        ),
    ]
