# Generated by Django 5.1.2 on 2026-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0012_global_pandit_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='user',
        ),
    ]
