# Generated by Django 5.1.2 on 2026-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_pandit_alter_chatroom_pandit_and_more'),
        ('pandits', '0013_remove_pandit_user'),
        ('payments', '0004_alter_panditwithdrawal_pandit'),
        ('reviews', '0003_alter_review_pandit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pandit',
        ),
    ]
