# Generated by Django 5.2.9 on 2026-01-04 15:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PujaTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('purchased_count', models.IntegerField(default=0)),
                ('user_feedback', models.CharField(choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful'), ('NO_FEEDBACK', 'No Feedback')], default='NO_FEEDBACK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamagriRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence score 0.0-1.0 based on historical data', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_essential', models.BooleanField(default=False, help_text='Cannot be removed from booking')),
                ('is_optional', models.BooleanField(default=False, help_text='User can choose to include or exclude')),
                ('priority', models.IntegerField(default=5, help_text='1=highest priority, 10=lowest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('category', models.CharField(choices=[('ESSENTIAL', 'Essential - Must Have'), ('TRADITIONAL', 'Traditional - Recommended'), ('OPTIONAL', 'Optional - Nice to Have'), ('LUXURY', 'Luxury - Premium Add-on')], default='TRADITIONAL', max_length=20)),
                ('quantity_min', models.IntegerField(default=1)),
                ('quantity_max', models.IntegerField(default=10)),
                ('quantity_default', models.IntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Why this item is recommended')),
                ('description', models.TextField(blank=True)),
                ('times_recommended', models.IntegerField(default=0)),
                ('times_purchased', models.IntegerField(default=0)),
                ('purchase_rate', models.FloatField(default=0.0, help_text='times_purchased / times_recommended')),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('seasonal_months', models.CharField(blank=True, help_text='Comma-separated months (1-12) when recommended', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_essential', '-confidence_score', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='UserSamagriPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_purchased', models.IntegerField(default=0)),
                ('last_purchased', models.DateTimeField(blank=True, null=True)),
                ('average_quantity', models.FloatField(default=1.0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('never_recommend', models.BooleanField(default=False, help_text="User doesn't want this item recommended")),
                ('prefer_bulk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_purchased', '-last_purchased'],
            },
        ),
        migrations.CreateModel(
            name='PujaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('puja_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('estimated_cost_with_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_for_pujas', models.ManyToManyField(blank=True, related_name='templates', to='services.puja')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
