# Generated by Django 5.2.9 on 2026-01-04 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_bookingsamagriitem_samagri_item_and_more'),
        ('recommender', '0001_initial'),
        ('samagri', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pujatemplateitem',
            name='samagri_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_inclusions', to='samagri.samagriitem'),
        ),
        migrations.AddField(
            model_name='pujatemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samagri_items', to='recommender.pujatemplate'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samagrirecommendation',
            name='puja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samagri_recommendations', to='services.puja'),
        ),
        migrations.AddField(
            model_name='samagrirecommendation',
            name='samagri_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puja_recommendations', to='samagri.samagriitem'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='recommendations',
            field=models.ManyToManyField(related_name='shown_in_logs', to='recommender.samagrirecommendation'),
        ),
        migrations.AddField(
            model_name='usersamagripreference',
            name='samagri_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='samagri.samagriitem'),
        ),
        migrations.AddField(
            model_name='usersamagripreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samagri_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pujatemplate',
            index=models.Index(fields=['puja_type', 'is_active'], name='recommender_puja_ty_5957b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pujatemplateitem',
            unique_together={('template', 'samagri_item')},
        ),
        migrations.AddIndex(
            model_name='samagrirecommendation',
            index=models.Index(fields=['puja', 'is_active'], name='recommender_puja_id_b43d19_idx'),
        ),
        migrations.AddIndex(
            model_name='samagrirecommendation',
            index=models.Index(fields=['confidence_score'], name='recommender_confide_dbe0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='samagrirecommendation',
            index=models.Index(fields=['category'], name='recommender_categor_561ece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='samagrirecommendation',
            unique_together={('puja', 'samagri_item')},
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', '-created_at'], name='recommender_user_id_be9887_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['booking'], name='recommender_booking_873999_idx'),
        ),
        migrations.AddIndex(
            model_name='usersamagripreference',
            index=models.Index(fields=['user', 'is_favorite'], name='recommender_user_id_b0fec4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersamagripreference',
            index=models.Index(fields=['user', 'times_purchased'], name='recommender_user_id_cd16d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersamagripreference',
            unique_together={('user', 'samagri_item')},
        ),
    ]
