# Generated by Django 5.1.2 on 2026-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanchangData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bs_date', models.CharField(max_length=50)),
                ('bs_year', models.IntegerField()),
                ('bs_month', models.IntegerField()),
                ('bs_day', models.IntegerField()),
                ('tithi', models.CharField(max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=100, null=True)),
                ('yoga', models.CharField(blank=True, max_length=100, null=True)),
                ('karana', models.CharField(blank=True, max_length=100, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('festivals', models.JSONField(blank=True, default=list)),
                ('muhurat_hints', models.TextField(blank=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panchang Data',
                'verbose_name_plural': 'Panchang Data',
                'ordering': ['-date'],
            },
        ),
    ]
