# Generated by Django 5.2.9 on 2025-12-31 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_rename_fee_booking_samagri_fee_booking_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('PANDIT_VERIFIED', 'Pandit Verified'), ('PANDIT_REJECTED', 'Pandit Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('title_ne', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (Nepali)')),
                ('message', models.TextField()),
                ('message_ne', models.TextField(blank=True, null=True, verbose_name='Message (Nepali)')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
