# Generated by Django 5.1.2 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('BOOKING_CREATED', 'Booking Created'),
                    ('BOOKING_ACCEPTED', 'Booking Accepted'),
                    ('BOOKING_COMPLETED', 'Booking Completed'),
                    ('BOOKING_CANCELLED', 'Booking Cancelled'),
                    ('PAYMENT_SUCCESS', 'Payment Successful'),
                    ('PAYMENT_FAILED', 'Payment Failed'),
                    ('NEW_MESSAGE', 'New Message'),
                    ('REVIEW_RECEIVED', 'Review Received'),
                    ('PANDIT_VERIFIED', 'Pandit Verified'),
                    ('PANDIT_REJECTED', 'Pandit Rejected'),
                    ('REMINDER', 'Reminder'),
                    ('PUJA_ROOM_READY', 'Puja Room Ready'),
                    ('VIDEO_CALL_INCOMING', 'Incoming Video Call'),
                    ('RECORDING_READY_REVIEW', 'Recording Ready (Review Prompt)'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='PushNotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('subscription', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushnotificationtoken',
            index=models.Index(fields=['user', 'device_type'], name='notificatio_user_id_e84b58_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationtoken',
            index=models.Index(fields=['token'], name='notificatio_token_96fb56_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationtoken',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_16d088_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationtoken',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_user_push_token'),
        ),
    ]
