# Generated by Django 5.1.2 on 2026-03-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pushnotificationtoken_and_new_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushnotificationtoken',
            new_name='notificatio_user_id_dc35b7_idx',
            old_name='notificatio_user_id_e84b58_idx',
        ),
        migrations.RenameIndex(
            model_name='pushnotificationtoken',
            new_name='notificatio_token_01cdfc_idx',
            old_name='notificatio_token_96fb56_idx',
        ),
        migrations.RenameIndex(
            model_name='pushnotificationtoken',
            new_name='notificatio_is_acti_9b89fa_idx',
            old_name='notificatio_is_acti_16d088_idx',
        ),
    ]
