# Generated by Django 5.1.2 on 2026-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_notificatio_user_id_e84b58_idx_notificatio_user_id_dc35b7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('PANDIT_VERIFIED', 'Pandit Verified'), ('PANDIT_REJECTED', 'Pandit Rejected'), ('REMINDER', 'Reminder'), ('PUJA_ROOM_READY', 'Puja Room Ready'), ('VIDEO_CALL_INCOMING', 'Incoming Video Call'), ('VIDEO_CALL_MISSED', 'Video Call Missed'), ('RECORDING_READY_REVIEW', 'Recording Ready (Review Prompt)')], max_length=30),
        ),
    ]
