# Generated by Django 5.1.2 on 2026-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_emailtemplate_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
